services:
  - type: web
    name: phishing-detector
    runtime: python
    rootDir: phishing-detector
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
